### ISSUE TITLE
Clean UP & Dockerization eos2mrz

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2mrz#2]

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, after refactoring this model, it seems to work quite well. I deleted the .dvc and .h5 files, renamed run.py to main.py, adjusted service.py to fit the run api, and created a run.sh file. I submitted the PR for this model.

**Comment by GemmaTuron** [comment]
@pittmanriley 
I have merged the PR but I have stopped the actions manually to upload the latest version only. Can you please have a look at the git-lfs tracking and see if we need to track any file?
Which are the model checkpoints in this case?

**Comment by pittmanriley** [comment]
@GemmaTuron, sounds good I will look at this. I think I'm ready to submit the PR again, but I'm waiting to make sure my intuition is correct after posting a question on Slack.

**Comment by GemmaTuron** [comment]
Good!
To keep everyone updates:
This model does not have the checkpoints, only a .perl scrip that is not over the git limit.
There is nonetheless a older .joblib mock file that should be deleted and untracked. The whole .gitattributes could be removed

**Comment by GemmaTuron** [comment]
@pittmanriley 

The actions are failing, please check

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I posted a question to slack, but this model works fine when I test on my computer. The error in the actions is related to a failure to update the metadata to Airtable. Does this mean that I need to adjust the metadata.json file?

**Comment by GemmaTuron** [comment]
this model is ready
